### ISSUE TITLE
crash on mac 

### ISSUE THREAD

**Issue by xiebaiyuan** [charmbracelet/freeze#105]
macos.
                 ,xNMM.           ----------------------------------
               .OMMMMo            OS: macOS Sonoma 14.4.1 arm64
               lMM"               Host: MacBook Pro (16-inch, 2021)
     .;loddo:.  .olloddol;.       Kernel: Darwin 23.4.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:     Uptime: 6 days, 22 hours, 8 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.     Packages: 249 (brew), 11 (brew-cask)
 XMMMMMMMMMMMMMMMMMMMMMMMX.       Shell: zsh 5.9
;MMMMMMMMMMMMMMMMMMMMMMMM:        Display (Color LCD): 4112x2658 @ 120Hz (as 2056x1329) [Built-in]
:MMMMMMMMMMMMMMMMMMMMMMMM:        DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.       WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.     WM Theme: Multicolor (Light)
 'XMMMMMMMMMMMMMMMMMMMMMMMMMMk    Font: .AppleSystemUIFont [System], Helvetica [User]
  'XMMMMMMMMMMMMMMMMMMMMMMMMK.    Cursor: Fill - Black, Outline - White (32px)
    kMMMMMMMMMMMMMMMMMMMMMMd      Terminal: Tabby 1.0.207
     ;KMMMMMMMWXXWMMMMMMMk.       Terminal Font: JetBrainsMono Nerd Font Mono (14pt)
       "cooc*"    "*coo'"         CPU: Apple M1 Max (10) @ 3.23 GHz
                                  GPU: Apple M1 Max (32) [Integrated]
                                  Memory: 29.48 GiB / 64.00 GiB (46%)
                                  Swap: Disabled
                                  Disk (/): 827.29 GiB / 926.35 GiB (89%) - apfs [Read-only]
                                  Local IP (utun4): 198.19.0.1/24 *
                                  Battery: 84% [AC connected]
                                  Power Adapter: 140W USB-C Power Adapter
                                  Locale: en_US.UTF-8

                                  ████████████████████████
                                  ████████████████████████

-------------------------------------------------------------------------------------------

freeze llama.h -o llama.png
thread '<unnamed>' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
                                
   ERROR  Unable to write output
                                
  wasm error: unreachable       
  wasm stack trace:             
      .$831()                   
      .$327(i32,i32,i32,i32,i32)
      .$839(i32)                
      .$838(i32)                
      .$168(i32)                
      .$131(i32,i32)            
      .$65()                    
      .$89(i32,i32,i32)         
      .$88(i32,i32,i32)         
      .$1623(i32,i32,i32)

**Comment by AlejandroSuero** [comment]
```bash
> neofetch
                    'c.          
                 ,xNMM.          ---------------------------------
               .OMMMMo           OS: macOS 14.5 23F79 arm64
               OMMM0,            Host: MacBookPro17,1
     .;loddo:' loolloddol;.      Kernel: 23.5.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 1 hour, 38 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 231 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.9
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1680x1050, 2560x1440
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: yabai
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    Terminal: tmux
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   CPU: Apple M1
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   GPU: Apple M1
    kMMMMMMMMMMMMMMMMMMMMMMd     Memory: 1170MiB / 8192MiB
     ;KMMMMMMMWXXWMMMMMMMk.
       .cooc,.    .,coo:.
```

@xiebaiyuan I don't seem to get anything out with `RUST_BACKTRACE=1`, neither it's crashing in my end.

https://github.com/charmbracelet/freeze/assets/71392160/310095ea-6d1f-4370-bb1a-e6f461acd1d4

The only package that I think it could be failing would be [resvg-go](https://github.com/kanrichan/resvg-go) or the usage of [librsvg](https://github.com/GNOME/librsvg) cli.

But in my end at least, is not crashing with use of both of them.

**Comment by xiebaiyuan** [comment]
ok. ill try my best..  thx

**Comment by amlugnaur** [comment]
**I've a similar issue on Windows 10** 

c:\work\test>freeze sql.sql --output sql.png
thread '<unnamed>' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

   ERROR  Unable to write output

  wasm error: unreachable
  wasm stack trace:
      .$831()
      .$327(i32,i32,i32,i32,i32)
      .$839(i32)
      .$838(i32)
      .$168(i32)
      .$131(i32,i32)
      .$65()
      .$89(i32,i32,i32)
      .$88(i32,i32,i32)
      .$1623(i32,i32,i32)

it works if I specify a defined font size it works, generating a pretty huge image (a lot of code !)

c:\work\test>freeze sql.sql --output sql.png --font.size 10
