### ISSUE TITLE
improve error message for `-x`

### ISSUE THREAD

**Issue by bashbunni** [charmbracelet/freeze#118]
if there's an error when we execute a command, ideally we should show that in our error message
![image](https://github.com/user-attachments/assets/6d7c3ece-d7c8-4a62-b29d-797d13512474)

was actually a "file not found" error for the go program I was trying to run

**Comment by AlejandroSuero** [comment]
@bashbunni I made the changes to improve the message shown when the command fails. If there is something to improve or add, all is welcomed.
