### ISSUE TITLE
"brew install freeze" installs another cask application called "freeze"

### ISSUE THREAD

**Issue by AlexW00** [charmbracelet/freeze#37]
i ran `brew install freeze` but it installed some random aws (cask) app. how can i install freeze on macos?

**Comment by maaslalani** [comment]
Hi @AlexW00, thanks for the issue:


You can use our `tap` to install freeze, I also updated the docs as well.

```
brew install charmbracelet/tap/freeze
```

**Comment by AlexW00** [comment]
awesome, thanks!
