### ISSUE TITLE
[Nix] README give incorrect install instructions

### ISSUE THREAD

**Issue by elythh** [charmbracelet/freeze#43]
**Describe the bug**
Freeze on the nixpkgs is not charm/freeze

**To Reproduce**
1. Go to 'https://search.nixos.org/packages'
2. Search for `freeze`
3. The result is [this](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/security/freeze/default.nix#L30)

**Expected behavior**
freeze should be available in the nixpkgs under the name freeze

**Additional context**
Just a documentation/Temporary issue.

**Comment by maaslalani** [comment]
Thanks so much @elythh, `freeze` will be available as `charm-freeze`.

https://github.com/NixOS/nixpkgs/pull/299189

I will update the documentation.

**Comment by zDyanTB** [comment]
> Thanks so much @elythh, `freeze` will be available as `charm-freeze`.

When it'll be on [nixpkgs](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=charm-freeze)?

**Comment by elythh** [comment]
The PR get merged 9 hours ago so it should be soon available in the unstable branch

**Comment by meowgorithm** [comment]
As a side note, Freeze, as well as our other applications, are also always available in the [Charm Nix User Repository](https://github.com/charmbracelet/nur).

**Comment by elythh** [comment]
> As a side note, Freeze, as well as our other applications, are also always available in the Charm Nix User Repository.

Oh sweet, didn't know there was a charm NUR, thank you !
