### ISSUE TITLE
bug: `freeze --execute` outputs "unsupported" [Windows]

### ISSUE THREAD

**Issue by SenZmaKi** [charmbracelet/freeze#46]
When I execute `freeze --execute "dir"` or any command aside from dir  I get 
```
ERROR: Something went wrong
unsupported
```
if `--execute` isn't supported on windows an explicit disclaimer would be nice

![image](https://github.com/charmbracelet/freeze/assets/90490506/aaa168ef-3ccd-4bb4-8ec9-098626321133)

 - OS: Microsoft Windows 11 Pro
 -  Version: 10.0.22631 N/A Build 22631

**Comment by lost22git** [comment]
Charm‘s apps never care about windows platform ;-)

**Comment by SenZmaKi** [comment]
> # A COMMON SENSE:
> **Charm‘s apps never care about windows platform ;-)**

In that case why not add a disclaimer that some features don't work on windows

**Comment by maaslalani** [comment]
Hey @SenZmaKi, thanks for opening this issue!

First class windows support is quite important to us so we'll work on getting a fix in soon.

The current implementation of `--execute` uses [`creak/pty`](https://github.com/creack/pty) to open a PTY which is [unsupported on Windows](https://github.com/creack/pty/blob/08e77a045af86a5b8300dc7b86e04ce71730a40c/start_windows.go#L18), but we will use our internal [`conpty`](https://github.com/charmbracelet/x/tree/main/exp/term/conpty) to get that supported. Very sorry that's not in currently!

Please let us know if you run into any other issues on Windows as well!

**Comment by maaslalani** [comment]
@lost22git @SenZmaKi

Windows `--execute` is now working!

```bash
freeze --execute "cmd /c dir"
```

![image](https://github.com/charmbracelet/freeze/assets/42545625/4d8ba876-b149-41f5-87e8-d6ccc499763a)
