### ISSUE TITLE
Command execution output is misaligned

### ISSUE THREAD

**Issue by GianniBYoung** [charmbracelet/freeze#47]
**Describe the bug**
When running commands that produce columnar output the alignment can be off

**To Reproduce**
1. freeze -x 'tokei usds_linux_base' -o linuxbase.png
2. See misaligned output

**Expected behavior**
I would expect the output to be lined up like the native commands output.

**Screenshots**
![image](https://github.com/charmbracelet/freeze/assets/43043456/e38eb9f1-ef65-4b69-a404-38832ca99c99)

**Desktop (please complete the following information):**
 - OS: Mac
 - Version 14.3.1
 - Kitty terminal 0.33

**Comment by maaslalani** [comment]
Thanks for the issue, seems like we're incorrectly handling tabbed output.

**Comment by maaslalani** [comment]
Hi @GianniBYoung, I added tabstops in https://github.com/charmbracelet/freeze/commit/5039d192949a3031511b42222ba4c6239f87c5a8.

Let me know if this solves the issue for you!

![freeze](https://github.com/charmbracelet/freeze/assets/42545625/7f5c07a6-613e-4766-9cf1-dccdbcf1291b)

**Comment by Zik42** [comment]
Still here for command `freeze --execute "eza -lah"`

```
❯ brew info charmbracelet/tap/freeze
==> charmbracelet/tap/freeze: stable 0.1.6
Generate images of code and terminal output.
https://charm.sh/
Installed
/opt/homebrew/Cellar/freeze/0.1.6 (6 files, 12.6MB) *
  Built from source on 2025-03-15 at 08:28:49
From: https://github.com/charmbracelet/homebrew-tap/blob/HEAD/freeze.rb
```
