### ISSUE TITLE
talk a code snap from line to line

### ISSUE THREAD

**Issue by Mahmoudgalalz** [charmbracelet/freeze#48]
be able to export from line-to-line code

would be nice if it had an interactive way, but I can work on a solution that cut it from line to line as an option, my solution would be instead of passing the whole file, pip it through cut or select then give the output to freeze

`cat src/index.ts | head -n 2 | tail -n +1 | freeze code.ts -o test.png --language javascript`

This is what I do to do that mission, so it would be nice if we could do it within freeze auto

**Comment by maaslalani** [comment]
Hey @Mahmoudgalalz, thanks for opening this issue!

Have you tried the `--lines` flag?

```
freeze src/index.ts --lines 3,-1 --output test.png --language javascript
```

**Comment by Mahmoudgalalz** [comment]
oh, it works
Thanks, need to document that
