### ISSUE TITLE
Freeze is not available in the Arch Repository

### ISSUE THREAD

**Issue by Mangeshrex** [charmbracelet/freeze#54]
![no](https://github.com/charmbracelet/freeze/assets/82205152/015d14c1-9c33-4d3f-9b8f-c04c85f8f5b0)

Hi Just saw the twitter post and I really felt like its the tool I need every day. While I was installing I found out that it looks like Freeze is not yet downloadable on Arch Linux via Pacman, but yet it is mentioned in the README. Is it really not up in the Arch Repository or am I missing something ? 

Tho, I've downloaded the Binary! 

Thank You

**Comment by FoxxMD** [comment]
It's packaged as [`freeze-bin`](https://aur.archlinux.org/packages/freeze-bin)

**Comment by caarlos0** [comment]
yes that's correct

thanks @FoxxMD
