### ISSUE TITLE
missing line numbering from default configuration file

### ISSUE THREAD

**Issue by darkspacer** [charmbracelet/freeze#63]
I don't speak English. This is an automatic translation from Google. 

I created a default configuration file by running the program interactively, however when I changed the value of the "lines_numbers" parameter the line numbering was missing, but I fixed it by changing the parameter name to "show_line_numbers". I think the problem is that this parameter is named incorrectly, and I hope this gets fixed soon.

**Comment by maaslalani** [comment]
Hey @darkspacer, thank you so much for using freeze and creating this issue! It is now fixed with in the following commit:

* https://github.com/charmbracelet/freeze/commit/974eec259d1c83dccc5e30fbaa124034dfc367ba
