### ISSUE TITLE
Add -v flag to get the version of binary

### ISSUE THREAD

**Issue by sgaunet** [charmbracelet/freeze#72]
**Is your feature request related to a problem? Please describe.**
Nop, just to be as all your other tools, I would like to get the binary version with the -v flag.

**Describe the solution you'd like**
"freeze -v" command should print the version of the binary

Thanks for all the wonderful tools

**Comment by maaslalani** [comment]
Hey @sgaunet, this is implemented in https://github.com/charmbracelet/freeze/pull/69!

Thank you for opening this issue, the `--version` flag will be included in the next release!
