### ISSUE TITLE
feat(colors): matching the theme from editor colorscheme

### ISSUE THREAD

**Issue by AlejandroSuero** [charmbracelet/freeze#94]
# Motivation

I am using `freeze` with the `rose-pine-moon` colour scheme because is what I use on **Neovim**, but the colours don't seem to match.

## Examples

- Using freeze:

![image generated by freeze](https://github.com/charmbracelet/freeze/assets/71392160/cce329df-5866-4324-a3c5-891ee8f6aaae)

- From screenshot:

![image from screenshot](https://github.com/charmbracelet/freeze/assets/71392160/f9b16b83-4c72-4333-8f6f-e76b5e58cc45)

## Additional context

- OS: `MacOS 14.4.1`.
- Editor: `Neovim v0.9.5`.
- Colorscheme: `rose-pine-moon`. (in both editor and `freeze`)

**Comment by meowgorithm** [comment]
It can be a such a bummer when theme implementations differ! The color scheme is defined upstream in [Chroma](https://github.com/alecthomas/chroma), so I'd file an issue (or PR) upstream. Here's the definition:

https://github.com/alecthomas/chroma/blob/master/styles/rose-pine-moon.xml

**Comment by caarlos0** [comment]
just fwiw: if you have semantic tokens enabled in your LSP, that might change colors as well

**Comment by AlejandroSuero** [comment]
@caarlos0 I know, but at least with [rose-pine default options](https://github.com/rose-pine/neovim?tab=readme-ov-file#options) doesn't seem to have them.

**Comment by AlejandroSuero** [comment]
@meowgorithm I will do that then.
